config/routes.rb
UsedCars::Application.routes.draw do

  resources :sessions
  resources :sellers do
    resources :cars do
      resources :comments
    end
  end

  match '/login', :to => 'sessions#new'
  match '/signup', :to => 'sellers#new'
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure/', :to => 'sessions#failure'
  match '/signout', :to => 'sessions#destroy', :as => :signout

  match 'sellers/results' => 'cars#results'
  match '/details' => 'cars#show'

  match 'sellers/compare' => 'cars#show'
  match '/used' => 'pages#used'
  match '/contact' => 'pages#contact'
  match '/about' => 'pages#about'

end

app/models/seller.rb
class Seller < ActiveRecord::Base
validates :name, :phone, :email, :city, :presence => true
validates :phone, :numericality => true
validates :email, :format => { :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i}

has_many :authorizations
has_many :cars
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController

skip_before_filter :require_seller, :only => [:index]
  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all
    @authorization = Authorization.new
    @cars = Car.new
   
    @selected_brand = params[:brand]
    @selected_model = params[:model]
    if params[:brand] != nil
      @toshow = Car.where({ :brand => [@selected_brand], :model => [@selected_model]}).all
      render 'sellers/results'
    end

    @compare_cars = params[:cars_ids]
    if params[:cars_ids] != nil
      @tofilter = Car.where({ :id => [@compare_cars]}).all
      render 'sellers/compare'
    end
   # respond_to do |format|
    #  format.html # index.html.erb
     # format.json { render json: @sellers }
    #end
  end
def results
end
  # GET /sellers/1
  # GET /sellers/1.json
  def show
    @seller = Seller.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @seller }
    end
  end

  # GET /sellers/new
  # GET /sellers/new.json
  def new
    @seller = Seller.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @seller }
    end
  end

  # GET /sellers/1/edit
  def edit
    @seller = Seller.find(params[:id])
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(params[:seller])

    respond_to do |format|
      if @seller.save
        format.html { redirect_to @seller, notice: 'Seller was successfully created.' }
        format.json { render json: @seller, status: :created, location: @seller }
      else
        format.html { render action: "new" }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sellers/1
  # PUT /sellers/1.json
  def update
    @seller = Seller.find(params[:id])

    respond_to do |format|
      if @seller.update_attributes(params[:seller])
        format.html { redirect_to @seller, notice: 'Seller was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller = Seller.find(params[:id])
    @seller.destroy

    respond_to do |format|
      format.html { redirect_to sellers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/_form.html.erb
<% if current_seller %>
<%= form_for(@seller) do |f| %>
<%= f.error_messages %>
  <% if @seller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seller.errors.count, "error") %> prohibited this seller from being saved:</h2>

      <ul>
      <% @seller.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
   <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<% else %>
<div class="alert alert-error">
<%= render :text => "You have to login with your facebook account to register as a Seller or Edit Your Profile. Login with your Facebook through the upper link" %>
</div>
<% end %>

app/views/sellers/_search.html.erb
<form name="searchcars">
<select name="brand" size="1" onChange="updatemodel(this.selectedIndex)" style="width: 150px">
<option selected>Select Brand...</option>
<option value="Opel">Opel</option>
<option value="Cheverolet">Cheverolet</option>
<option value="Skoda">Skoda</option>
</select>

<select name="model" size="1" style="width: 150px">
</select>
<br />
<div align="center"> <input type="submit" value="Search Cars"></div>
</form>

<script type="text/javascript">

var brandlist=document.searchcars.brand
var modellist=document.searchcars.model

var model=new Array()
model[0]=""
model[1]=["Vectra|Vectra", "Corsa|Corsa"]
model[2]=["Optra|Optra", "Lanos|Lanos"]
model[3]=["Octavia|Octavia", "Fleshia|Fleshia"]

function updatemodel(selectedbrand){
modellist.options.length=0
if (selectedbrand>0){
for (i=0; i<model[selectedbrand].length; i++)
modellist.options[modellist.options.length]=new Option(model[selectedbrand][i].split("|")[0], model[selectedbrand][i].split("|")[1])
}
}

</script>

app/views/sellers/compare.html.erb
<%- model_class = Seller -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Brand</th>
      <th>Model</th>
      <th>Color</th>
      <th>Manu. Yr</th>
      <th>Mileage</th>
      <th>Motor CC</th>
      <th>Transmission</th>
      <th>AC</th>
      <th>Power Steering</th>
      <th>Electric Glasses</th>
      <th>Doors</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @tofilter.each do |item| %>
      <tr>
        <td><%= link_to item.id, details_path(@seller, :id => item) %></td>
        <td><%= item.brand %></td>
        <td><%= item.model %></td>
        <td><%= item.color %></td>
        <td><%= item.year %></td>
        <td><%= item.mileage %></td>
        <td><%= item.cc %></td>
        <td><%= item.transmission %></td>
        <td><%= item.ac %></td>
        <td><%= item.power_steering %></td>
        <td><%= item.electric_glasses %></td>
        <td><%= item.doors %></td>
        <td><%= item.notes %></td>
      </tr>
    <% end %>
   
    </tbody>

</table>

<b> Please click on the car ID to view seller's information. </b>

<%= link_to t('.back', :default => t("helpers.links.Back")),
              sellers_path, :class => 'btn'  %>

app/views/sellers/edit.html.erb
<h1>Editing seller</h1>

<%= render 'form' %>

app/views/sellers/index.html.erb
<%- model_class = Seller -%>
      
  <p class="lead">At our <strong>Global Used Cars portal</strong>, we make it easy and convenient for you to sell your car privately. We list your approved car and advertise it extensively, for FREE, to a wide audience of potential buyers. Once interest is shown in your car we will arrange a test drive in a safe & secure environment! We handle all the paperwork and arrange the transfer of ownership for you!   </p>
   
<% if current_seller %>
 

<% else %>

<%= link_to t('.new', :default => t("helpers.links.Register as a Seller!")),
            "auth/facebook",
            :class => 'btn btn-large btn-block' %>
<% end %>

app/views/sellers/new.html.erb
<h1>New seller</h1>

<%= render 'form' %>

<%= link_to 'Back', sellers_path %>

app/views/sellers/results.html.erb
<%- model_class = Seller -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<form name="compare">

<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:brand) %></th>
      <th><%= model_class.human_attribute_name(:model) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% @toshow.each do |item| %>
      <tr>
        <td><%= check_box_tag 'cars_ids[]', item.id %></td>
        <td><%= link_to item.id, details_path(@seller, :id => item) %></td>
        <td><%= item.brand %></td>
        <td><%= item.model %></td>
        <td><%= item.created_at %></td>
      </tr>
    <% end %>
   
    </tbody>

</table>
<div align="center"> <input type="submit" value="Search Cars"></div>
</form>
<b> Note: For more details on each car, please click on the car ID. </b>

app/views/sellers/show.html.erb
<% if current_seller %>
<p id="notice"><%= notice %></p>

<h2> Edit Profile</h>
<p>
  <b>Name:</b>
  <%= @seller.name %>
  <br />
  <b>Email:</b>
  <%= @seller.email %>
  <br />
  <b>City:</b>
  <%= @seller.city %>
  <br />
  <b>Phone:</b>
  <%= @seller.phone %>
  <br />
</p>

<%= link_to t('.back', :default => t("helpers.links.Back")),
              sellers_path, :class => 'btn'  %>
<%= link_to t('.edit', :default => t("helpers.links.Edit Your Profile")),
              edit_seller_path(@seller), :class => 'btn' %>

<%= link_to t('.manage', :default => t("helpers.links.Manage Your Sellings")),
              seller_cars_path(session[:seller_id]), :class => 'btn' %>
<% else %>
<div class="alert alert-error">
<%= render :text => "You have to login with your facebook account to register as a Seller or Edit Your Profile. Login with your Facebook through the upper link" %>
</div>
<% end %>