config/routes.rb
UsedCars::Application.routes.draw do

  resources :sessions
  resources :sellers do
    resources :cars do
      resources :comments
    end
  end

  match '/login', :to => 'sessions#new'
  match '/signup', :to => 'sellers#new'
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure/', :to => 'sessions#failure'
  match '/signout', :to => 'sessions#destroy', :as => :signout

  match 'sellers/results' => 'cars#results'
  match '/details' => 'cars#show'

  match 'sellers/compare' => 'cars#show'
  match '/used' => 'pages#used'
  match '/contact' => 'pages#contact'
  match '/about' => 'pages#about'

end

app/models/car.rb
class Car < ActiveRecord::Base
validates :mileage, :cc, :notes, :numericality => true
validates :brand, :model, :color, :year, :mileage, :cc, :notes, :presence =>true

belongs_to :seller
has_many :comments

  attr_accessible :photo, :brand, :model, :color, :year, :mileage, :cc, :transmission, :ac, :power_steering, :electric_glasses, :doors, :notes
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
skip_before_filter :require_seller, :only => [:show, :destroy]
  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
    #@cars = Car.where({:seller_id => session[:seller_id]}).all
    #@seller = Seller.find(params[:id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    #@car = Car.new
    @seller = Seller.find(session[:seller_id])
    @car = @seller.cars.build
  
    #@car = Car.create(:seller_id => @seller.id)
    #@car = @seller.cars.create()
    #@seller.cars.create :seller_id => session[:seller_id]
    
    #respond_to do |format|
     # format.html # new.html.erb
      #format.json { render json: @car }
    #end
  end

  # GET /cars/1/edit
  def edit
    #@car = Car.find(params[:id])
    #@seller = Seller.find(session[:seller_id])
    @seller = Seller.find(params[:seller_id])
    @car = @seller.cars.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    #@car = Car.new (params[:car][:brand])
    @seller = Seller.find(params[:seller_id])
    #Correct @car = @seller.cars.build(:seller_id => @seller)
    @car = @seller.cars.build(params[:car])
    @car.save
    if @car.save
     flash[:notice] = "A New Car Advert Has Been Created!"
     redirect_to seller_url(@car.seller_id)
     
     else 
     render :action => 'new'
    end
  
    #render :text => "Test"
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    #@car = Car.find(params[:id])
    @seller = Seller.find(params[:seller_id])
    @car = @seller.cars.find(params[:id])
    if @car.update_attributes(params[:car])
    flash[:notice] = "Car advert successfully updated!"
    redirect_to seller_url(@car.seller_id)
    else
    render :action => 'edit'
    end
    #respond_to do |format|
     # if @car.update_attributes(params[:car])
      #  format.html { redirect_to @car, notice: 'Car was successfully updated.' }
       # format.json { head :ok }
      #else
       # format.html { render action: "edit" }
        #format.json { render json: @car.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @seller = Seller.find(params[:seller_id])
    @car = @seller.cars.find(params[:id])
    @car.destroy

     flash[:notice] = "Advert Deleted"
     redirect_to seller_cars_path(session[:seller_id])

     #respond_to do |format|
     #format.html { redirect_to cars_url }
     #format.json { head :ok }
     #end
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<% if current_seller %>
<%= form_for [@seller, @car] do |f| %>
<%= f.error_messages %>
 
  <div class="field">
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :year %>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :mileage %>
    <%= f.text_field :mileage %>
  </div>
  <div class="field">
    <%= f.label :cc %>
    <%= f.text_field :cc %>
  </div>
  <div class="field">
    <%= f.label :transmission %>
    <%= f.select :transmission, [['','nothing'],['Automatic','automatic'],['Manual','manual']] %>
  </div>
  <div class="field">
    <%= f.label :ac %>
    <%= f.select :ac, [['','nothing'],['Yes','yes'],['No','no']] %>
  </div>
  <div class="field">
    <%= f.label :power_steering %>
    <%= f.select :power_steering, [['','nothing'],['Yes','yes'],['No','no']] %>
  </div>
  <div class="field">
    <%= f.label :electric_glasses %>
    <%= f.select :electric_glasses, [['','nothing'],['Yes','yes'],['No','no']] %>
  </div>
  <div class="field">
    <%= f.label :doors %>
    <%= f.select :doors, [['','nothing'],['Two','two'],['Four','four']] %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :notes %>
  </div>
<div class="field">
    <%= f.label :car_photo %>
    <%= f.file_field :photo %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to t('.back', :default => t("helpers.links.Cancel")),
              seller_cars_path(session[:seller_id]), :class => 'btn'  %>

<% else %>
<div class="alert alert-error">
<%= render :text => "You have to be a registered Seller to add or modify a car advert. Login with your Facebook through the upper link" %>
</div>
<% end %>

app/views/cars/_search.html.erb
<form name="searchcars">
<select name="brand" size="1" onChange="updatemodel(this.selectedIndex)" style="width: 150px">
<option selected>Select Brand...</option>
<option value="Opel">Opel</option>
<option value="Cheverolet">Cheverolet</option>
<option value="Skoda">Skoda</option>
</select>

<select name="model" size="1" style="width: 150px">
</select>
<br />
<div align="center"> <input type="submit" value="Search Cars"></div>
</form>

<script type="text/javascript">

var brandlist=document.searchcars.brand
var modellist=document.searchcars.model

var model=new Array()
model[0]=""
model[1]=["Vectra|Vectra", "Corsa|Corsa"]
model[2]=["Optra|Optra", "Lanos|Lanos"]
model[3]=["Octavia|Octavia", "Fleshia|Fleshia"]

function updatemodel(selectedbrand){
modellist.options.length=0
if (selectedbrand>0){
for (i=0; i<model[selectedbrand].length; i++)
modellist.options[modellist.options.length]=new Option(model[selectedbrand][i].split("|")[0], model[selectedbrand][i].split("|")[1])
}
}

</script>

app/views/cars/edit.html.erb
<h1>Edit Car Advert</h1>

<%= render 'form' %>

app/views/cars/index.html.erb
<% if current_seller %>
<h1>Listing cars</h1>

<table class="table table-hover">
  <tr>
    <th>Brand</th>
    <th>Model</th>
  </tr>

<% @cars.each do |car| %>
  <tr>
    <td><%= car.brand %></td>
    <td><%= car.model%></td>
    <td><%= link_to t('.edit', :default => t("helpers.links.Edit Car Info")),
              edit_seller_car_path(session[:seller_id], car), :class => 'btn' %></td>
    <td> <%= link_to t('.destroy', :default => t("helpers.links.Delete Advert")),
              seller_car_path(session[:seller_id], car),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %></td>
  </tr>
  
<% end %>
</table>
<%= link_to "Sell a Car", new_seller_car_path(session[:seller_id]), :class => 'btn' %>
<%= link_to t('.back', :default => t("helpers.links.Back")),
              seller_path(session[:seller_id]), :class => 'btn'  %>
<br />

<% else %>
<div class="alert alert-error">
<%= render :text => "You have to be a registered Seller. Login with your Facebook through the upper link" %>
</div>
<% end %>

app/views/cars/new.html.erb
<h1>New Car Advert</h1>

<%= render 'form' %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<h3> Car Details </h3>
  <b>Brand:</b>
  <%= @car.brand %>
  <br />
  <b> Model: </b>
  <%= @car.model %>
  <br />
  <b> Color: </b>
  <%= @car.color %>
  <br />
  <b> Manufacturing Year: </b>
  <%= @car.year %>
  <br />
  <b> Mileage: </b>
  <%= @car.mileage %>
  <br />
  <b> Motor CC: </b>
  <%= @car.cc %>
  <br />
  <b> Transmission: </b>
  <%= @car.transmission %>
  <br />
  <b> AC: </b>
  <%= @car.ac %>
  <br />
  <b> Power Steering: </b>
  <%= @car.power_steering %>
  <br />
  <b> Electric Glasses: </b>
  <%= @car.electric_glasses %>
  <br />
  <b> Doors: </b>
  <%= @car.doors %>
  <br />
  <b> Price: </b>
  <%= @car.notes %>
  <br />
  <h3> Seller's Information </h3>
  <br />
  <b> Seller Name: </b>
  <%= @car.seller.name %>
  <br />
  <b> Email: </b>
  <%= @car.seller.email %>
  <br />
  <b> Location: </b>
  <%= @car.seller.city %>
  <br />
  <b> Phone: </b>
  <%= @car.seller.phone %>

</p>
<%= link_to t('.back', :default => t("helpers.links.Back")),
              sellers_path, :class => 'btn'  %>
<div class="fb-comments" data-href="http://localhost:3000/sellers" data-width="770" data-num-posts="2"></div>